### PR TITLE
enhanced scan update

### PR DESCRIPTION
**Pull request by sainathdev**
## Proposed changes
The new scanning method on the ECR is moved from Basic to enhanced. As a part of the update, AWS have not fixed few of the API's for which the scans are not reporting on the ecrscan dashboard. 
I have opened the ticket with AWS and the team is working on fixing the issue but there is a no ETA of the fix.
The PR provides update of getting the ECRSCAN report from the enhanced scanning feature.
Please review.
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [ ] I have filled out this PR template
- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

### CODE REVIEW

**Comment by sainathdev** [comment]
@bjfish25  Please review.

**Comment by sainathdev** [comment]
@shubydo Please review.

**Review by bjfish25 — APPROVED** [review]
This looks good to me. Note: This bug fix dramatically increases run time from seconds to minutes, so we need to ensure we check often to see if bug is fixed.

An option for improvement could be modeling GetECRImageScanFindings closer to GetECRImagesWithTag and return the image.
This way we can then check the ImageScanStatus of the new method in convertScanFindings, and return a nil otherwise

**Comment by rajholla** [comment]
> This looks good to me. Note: This bug fix dramatically increases run time from seconds to minutes, so we need to ensure we check often to see if bug is fixed.
> 
> An option for improvement could be modeling GetECRImageScanFindings closer to GetECRImagesWithTag and return the image. This way we can then check the ImageScanStatus of the new method in convertScanFindings, and return a nil otherwise

If this is going to be fixed by AWS, I would rather wait and use the build from this branch meantime. 
Not sure merging to master is a good idea.

**Comment by bjfish25** [comment]
Released in https://github.com/Optum/cloudig/releases/tag/v0.1.6 but not merged with the idea this will be eventually patched by AWS

**Pull request closed without merging**
